export default [
    { lastName: 'Shakur', firstName: 'Tupac Amaru', username: '2Pac', email: '2pac.deathrow@gmail.com' },
    {
        lastName: 'Wallace',
        firstName: 'Christopher',
        username: 'The Notorious B.I.G.',
        email: 'biggiesmalls@gmail.com',
    },
    { lastName: 'Wright', firstName: 'Eric', username: 'Eazy E', email: 'EazyMuthaphuckkinE@gmail.com' },
    { lastName: 'Cordozar', firstName: 'Calvin', username: 'Snoop Dogg', email: 'snoop420@gmail.com' },
    { lastName: 'Diggs', firstName: 'Robert', username: 'The RZA', email: 'bobby.wutangclan@gmail.com' },
    { lastName: 'West', firstName: 'Kanye', username: 'Ye', email: 'yeezus@gmail.com' },
    { lastName: 'Mathers III', firstName: 'Marshall', username: 'Eminem', email: 'slim.shady@gmail.com' },
    { lastName: 'Webster', firstName: 'Jacques', username: 'Travis Scott', email: 'utopia@gmail.com' },
    { lastName: 'Kirk', firstName: 'Jonathan', username: 'Dababy', email: 'ReelGoats@gmail.com' },
    { lastName: 'Fenty', firstName: 'Robyn', username: 'Rihanna', email: 'rihanna@gmail.com' },
    { lastName: 'Almánzar', firstName: 'Belcalis', username: 'Cardi B', email: 'cardib@gmail.com' },
    {
        lastName: 'Knowles',
        firstName: 'Beyoncé',
        username: 'Beyoncé ',
        email: 'parkwood.entertainment@gmail.com',
    },
    { lastName: 'Cook', firstName: 'Alicia', username: 'Alicia Keys', email: 'nystateofmind@gmail.com' },
    { lastName: 'Winehouse', firstName: 'Amy', username: 'Amy Winehouse', email: 'winehouse@gmail.com' },
    { lastName: 'Johnson', firstName: 'Robert', username: 'Robert Johnson', email: 'thefirstofall@gmail.com' },
    { lastName: 'Marley', firstName: 'Robert Nesta', username: 'Bob Marley', email: 'thewailers@gmail.com' },
    { lastName: 'Lennon', firstName: 'John Winston', username: 'John Lennon', email: 'fromabbeyroad@gmail.com' },
]
